# application-Dev.properties
private-key=${PRIVATE_KEY}
mp.jwt.verify.issuer=mariorusso
mp.jwt.verify.publickey.location=${PUBLIC_KEY}
quarkus.native.resources.includes=${PUBLIC_KEY}

quarkus.datasource.db-kind=${KIND}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/banco}

# Ativa o CORS
quarkus.http.cors.enabled=true
# Dominios permitidos (use * para todos)
quarkus.http.cors.origins=*

# Metodos HTTP permitidos
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS,PATCH

# Headers permitidos
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# Headers expostos para o cliente
quarkus.http.cors.exposed-headers=location,info
