# application-Dev.properties
private-key=${PRIVATE_KEY}
mp.jwt.verify.issuer=mariorusso
mp.jwt.verify.publickey.location=${PUBLIC_KEY}
quarkus.native.resources.includes=${PUBLIC_KEY}

quarkus.datasource.db-kind=${KIND}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/banco}

