# build
FROM node:22-alpine AS build
WORKDIR /app

COPY . .
RUN npm install --legacy-peer-deps
RUN npm run build

# nginx
FROM nginx:alpine
COPY --from=build /app/dist/spa /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
CMD ["/bin/sh", "-c", "sed -i 's|__VITE_API_URL_PLACEHOLDER__|'\"$VITE_API_URL\"'|g' /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
